# Regions to remove resources from
regions:
- "global"
- "us-east-1"
- "ca-central-1"

# Only delete resources from this account that do not match the filters
accounts:
  "124044056575":
    filters:
      CloudFormationStack:
        - propery: Name
          type: regex
          value: ".*(Landing-?Zone|cloud-based-sensor).*"
      CloudTrailTrail:
        - propery: Name
          type: regex
          value: "(.*Landing-?Zone.*|CbsSatelliteTrail)"
      CloudWatchAlarm:
        - propery: TargetId
          type: regex
          value: "(CloudTrail.*|IAMPolicyChanges|RootLogin|Cbs.*|cbs-.*|secops.*)"
      CloudWatchEventsTarget:
        - propery: Name
          type: regex
          value: ".*Landing-?Zone.*"
      CloudWatchLogsLogGroup:
        - propery: ARN
          type: regex
          value: "(.*Landing-?Zone|Cbs|cbs-|secops).*"
      IAMPolicy:
        - propery: PolicyName
          type: regex
          value: "(cbs-|Cbs|ConfigTerraform|secops).*"
      IAMRole:
        - propery: Name
          type: regex
          value: "(Landing-?Zone|AWSReservedSSO|CloudFormation|Cbs.*|cbs-.*|ConfigTerraform.*|secops.*)"
      IAMRolePolicy:
        - propery: RoleName
          type: regex
          value: "(Landing-?Zone|AWSReservedSSO|CloudFormation|Cbs.*|cbs-.*|secops.*)"
      IAMRolePolicyAttachment:
        - propery: RoleName
          type: regex
          value: "(Landing-?Zone|AWSReservedSSO|Cbs.*|cbs-.*|ConfigTerraform.*|secops.*)"
      LambdaFunction:
        - propery: Name
          type: regex
          value: "(.*Landing-?Zone|Cbs|cbs-|secops).*"
      S3Bucket:
        - propery: BucketName
          type: regex
          value: "(cbs-|secops).*"
      S3Object:
        - propery: BucketName
          type: regex
          value: "(cbs-|secops).*"
      SNSSubscription:
        - propery: ARN
          type: regex
          value: ".*(Landing-?Zone|Cbs|cbs-|secops).*"
      SNSTopic:
        - propery: TopicARN
          type: regex
          value: ".*(Landing-?Zone|Cbs|cbs-|secops).*"
      SSMParameter:
        - propery: Name
          type: regex
          value: "(.*local_sns_arn|secops).*"

# Do not delete any of the following resource types
resource-types:
  excludes:
    - CloudWatchEventsRule
    - ConfigServiceConfigRule
    - ConfigServiceDeliveryChannel
    - ConfigServiceConfigurationRecorder
    - EC2DHCPOption
    - ElasticacheCacheParameterGroup
    - FMSPolicy
    - FMSNotificationChannel
    - GuardDutyDetector
    - IAMUserAccessKey
    - IAMUserPolicyAttachment
    - IAMLoginProfile
    - IAMOpenIDConnectProvider
    - IAMSAMLProvider
    - IAMUser
    - KMSAlias
    - KMSKey
    - OpsWorksUserProfile
    - SecurityHub

# Accounts that will not have resources removed
account-blocklist:
- "005133826942"
- "136676205420"
- "239043911459"
- "276192857112"
- "283582579564"
- "296255494825"
- "339850311124"
- "349837941862"
- "370045664819"
- "400061975867"
- "406214159830"
- "414662622316"
- "472286471787"
- "507252742351"
- "537819865265"
- "563894450011"
- "591111259917"
- "595701125956"
- "637287734259"
- "687401027353"
- "703399696403"
- "729164266357"
- "773858180673"
- "794722365809"
- "797698708703"
- "806545929748"
- "820252213580"
- "843973686572"
- "871282759583"
- "925306372402"
- "957818836222"
- "977382588899"
