Parameters:
  AccessKeysRotatedParamMaxAccessKeyAge:
    Default: "90"
    Type: String
Resources:
  AccessKeysRotated:
    Properties:
      ConfigRuleName: access-keys-rotated
      InputParameters:
        maxAccessKeyAge:
          Fn::If:
            - accessKeysRotatedParamMaxAccessKeyAge
            - Ref: AccessKeysRotatedParamMaxAccessKeyAge
            - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: ACCESS_KEYS_ROTATED
    Type: AWS::Config::ConfigRule
  AlbHttpToHttpsRedirectionCheck:
    Properties:
      ConfigRuleName: alb-http-to-https-redirection-check
      Source:
        Owner: AWS
        SourceIdentifier: ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK
    Type: AWS::Config::ConfigRule
Conditions:
  accessKeysRotatedParamMaxAccessKeyAge:
    Fn::Not:
      - Fn::Equals:
          - ""
          - Ref: AccessKeysRotatedParamMaxAccessKeyAge
